/* ============================================================
   Renders the page from window.SITE_CONFIG (see config.js).
   You normally never need to touch this file.
   ============================================================ */
(function () {
  const cfg = window.SITE_CONFIG || {};

  /* ---- helper: read a possibly-nested key like "video.heading" */
  function get(path) {
    return path.split(".").reduce((o, k) => (o == null ? o : o[k]), cfg);
  }

  /* ---- 1. simple text bindings: [data-config="key"] ---------- */
  document.querySelectorAll("[data-config]").forEach((el) => {
    const val = get(el.getAttribute("data-config"));
    if (val != null && val !== "") el.textContent = val;
  });

  /* ---- 2. pull quotes ---------------------------------------- */
  document.querySelectorAll("[data-quote]").forEach((section) => {
    const q = (cfg.quotes || [])[Number(section.dataset.quote)];
    if (!q) { section.remove(); return; }
    const text = document.createElement("p");
    text.className = "quote-block__text";
    text.textContent = q.text;
    const attr = document.createElement("p");
    attr.className = "quote-block__attr";
    attr.textContent = q.attribution || "";
    section.append(text, attr);
  });

  /* ---- 3. gallery -------------------------------------------- */
  // Photo list comes from photos.js (auto-generated by sync-photos.sh).
  // Optional captions: add an entry to cfg.captions keyed by any part
  // of the filename, e.g. captions: { "IMG_7853": "That smile" }.
  const grid = document.getElementById("gallery-grid");
  if (grid) {
    const captions = cfg.captions || {};
    const photoList = (window.PHOTOS || []).map((src) => {
      const key = Object.keys(captions).find((k) => src.includes(k));
      return { src, caption: key ? captions[key] : "" };
    });
    photoList.forEach((photo) => {
      const item = document.createElement("figure");
      item.className = "gallery__item";

      const img = document.createElement("img");
      img.src = photo.src;
      img.alt = photo.caption || "A cherished memory";
      img.loading = "lazy";

      // Graceful fallback if a file isn't there yet
      img.addEventListener("error", () => {
        item.classList.add("gallery__item--placeholder");
        item.textContent = photo.caption || "Photo coming soon";
      });

      item.appendChild(img);

      if (photo.caption) {
        const cap = document.createElement("figcaption");
        cap.className = "gallery__caption";
        cap.textContent = photo.caption;
        item.appendChild(cap);
      }
      grid.appendChild(item);
    });
  }

  /* ---- 4. video ---------------------------------------------- */
  const videoSection = document.getElementById("video");
  const videoFrame = document.getElementById("video-frame");
  const v = cfg.video || {};
  if (videoSection && videoFrame && v.mode && v.mode !== "none") {
    if (v.mode === "youtube" && v.youtubeId) {
      const iframe = document.createElement("iframe");
      iframe.src = `https://www.youtube-nocookie.com/embed/${v.youtubeId}?rel=0`;
      iframe.title = v.heading || "Video";
      iframe.allow =
        "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture";
      iframe.allowFullscreen = true;
      videoFrame.appendChild(iframe);
      videoSection.hidden = false;
    } else if (v.mode === "mp4" && v.mp4Src) {
      const video = document.createElement("video");
      video.src = v.mp4Src;
      video.controls = true;
      video.playsInline = true;
      if (v.poster) video.poster = v.poster;
      // If the file isn't uploaded yet, hide the section instead of
      // showing a broken player.
      video.addEventListener("error", () => { videoSection.hidden = true; });
      videoFrame.appendChild(video);
      videoSection.hidden = false;
    }
  }

  /* ---- 5. scroll-reveal -------------------------------------- */
  const revealTargets = document.querySelectorAll(
    ".quote-block, .gallery, .video, .closing"
  );
  revealTargets.forEach((el) => el.classList.add("reveal"));

  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add("is-visible");
            io.unobserve(e.target);
          }
        });
      },
      { threshold: 0.15 }
    );
    revealTargets.forEach((el) => io.observe(el));
  } else {
    revealTargets.forEach((el) => el.classList.add("is-visible"));
  }
})();
