#!/usr/bin/env bash
# ============================================================
# Re-scan the /images folder and rebuild photos.js.
# Run this any time you ADD or REMOVE photos, then redeploy.
#
#   ./sync-photos.sh
#
# It also converts any HEIC files to JPG (so they show on every
# phone/browser, not just iPhones).
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

# 1. Convert any HEIC/HEIF to JPG (browsers can't show HEIC reliably)
shopt -s nullglob nocaseglob
for f in images/*.heic images/*.heif; do
  out="${f%.*}.jpg"
  if command -v sips >/dev/null 2>&1; then
    sips -s format jpeg "$f" --out "$out" >/dev/null 2>&1 && rm "$f" \
      && echo "converted $f -> $out"
  fi
done
# 2. Build photos.js from whatever images now exist (case-insensitive,
#    sorted, de-duplicated). Written to work on macOS's bash 3.2.
list="$(
  for f in images/*.jpg images/*.jpeg images/*.png images/*.webp; do
    [ -e "$f" ] && echo "$f"
  done | sort -u
)"
shopt -u nocaseglob

{
  echo "/* AUTO-GENERATED by sync-photos.sh — do not edit by hand. */"
  echo "window.PHOTOS = ["
  while IFS= read -r f; do
    [ -n "$f" ] && echo "  \"$f\","
  done <<< "$list"
  echo "];"
} > photos.js

count=$(grep -c '^  "' photos.js || true)
echo "photos.js rebuilt with $count photo(s)."
